### ISSUE TITLE
TypeError: Cannot read property 'ping' of undefined when pushing

### ISSUE THREAD

**Issue by samjarman** [parse-community/node-apn#50]
Node version: v14.15.5
OS: Ubuntu
Lib version: 4.0.0

I get the following error when sending a push (running `tail -f /var/log/syslog`):

```
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]: /home/myappnamehere/prod/node_modules/parse-server/lib/ParseServer.js:237
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]:           throw err;
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]:           ^
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]: TypeError: Cannot read property 'ping' of undefined
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]:     at ClientHttp2Session.ping (internal/http2/core.js:786:26)
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]:     at Timeout.Client.healthCheckInterval.setInterval [as _onTimeout] (/home/myappnamehere/prod/node_modules/@parse/node-apn/lib/client.js:29:22)
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]:     at ontimeout (timers.js:482:11)
Feb 14 22:33:36 myappnamehere-parse parse-server[105441]:     at Timer.unrefdHandle (timers.js:595:5)
Feb 14 22:33:36 myappnamehere-parse systemd[1]: parse-server.service: Main process exited, code=exited, status=7/NOTRUNNING
Feb 14 22:33:36 myappnamehere-parse systemd[1]: parse-server.service: Failed with result 'exit-code'.
Feb 14 22:33:39 myappnamehere-parse systemd[1]: parse-server.service: Service hold-off time over, scheduling restart.
Feb 14 22:33:39 myappnamehere-parse systemd[1]: parse-server.service: Scheduled restart job, restart counter is at 2.
Feb 14 22:33:39 myappnamehere-parse systemd[1]: Stopped Parse Server.
```

In the parse dashboard, I see the push(es) stuck in a "SENDING" state. 

Any ideas?

Thanks!

**Comment by davimacedo** [comment]
Could you please share your package.json and parse server configuration?

**Comment by samjarman** [comment]
Sorry, I should have followed up on this. 
Turns out AI was actually using node 8.x, which looks to be incompatible. The versions above work fine :)
